---
- hosts: localhost
  gather_facts: no
  vars:
    vault_addr: http://54.152.160.1:8200
    
  tasks:
    - name: get vault token
      shell: vault token create -policy={{ vault_policy }} | grep -w token | awk '{ print $NF }'
      register: token
      environment:
         VAULT_TOKEN: "{{ vault_token }}"
         VAULT_ADDR: "{{ vault_addr }}"
  
    - name: Set Token
      set_fact: use_this_token="{{ token.stdout }}"

    - name: get Vault AWS Credentials
      vault_secret: path=aws/creds/{{ aws_role }} vault_addr={{ vault_addr }} vault_token={{ use_this_token }}
      register: aws_creds
      ignore_errors: true

    - name: dump creds
      debug: msg="{{ aws_creds }}"
    